backend/project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("shortener.urls", namespace="shortener")),
]

backend/shortener/api/urls.py
from django.urls import path

from shortener.api.views import (
    AliasAvailabilityAPIView,
    LinkClicksListAPIView,
    LinkCreateAPIView,
    LinkListDestroyAPIView,
    OwnerCreateAPIView,
    OwnerRetrieveAPIView,
)

urlpatterns = [
    path("links/", LinkCreateAPIView.as_view(), name="link_create"),
    path("owner/", OwnerCreateAPIView.as_view(), name="owner_create"),
    path("owner/<uuid:pk>/", OwnerRetrieveAPIView.as_view(), name="owner_retrieve"),
    path("owner/<uuid:pk>/links/", LinkListDestroyAPIView.as_view(), name="link_list_destroy"),
    path(
        "owner/<uuid:owner>/links/<slug:alias>/clicks/",
        LinkClicksListAPIView.as_view(),
        name="link_clicks_list",
    ),
    path("alias-availablity/<slug:alias>/", AliasAvailabilityAPIView.as_view()),
]

backend/shortener/urls.py
from django.urls import include, path

from shortener.views import ToTargetView

app_name = "shortener"

urlpatterns = [
    path("go/<str:alias>/", ToTargetView.as_view(), name="to_target"),
    path("api/", include("shortener.api.urls")),
]

backend/shortener/models.py
import uuid

from django.db import models
from django.utils.crypto import get_random_string


def make_alias(length=8):
    return get_random_string(length=length)


class Owner(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    def __str__(self):
        return f"Owner {self.id}"


class Link(models.Model):
    alias = models.SlugField(primary_key=True, blank=True)
    target_url = models.URLField()
    password = models.CharField(max_length=12, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    expires_after = models.DateTimeField(null=True, blank=True)
    owner = models.ForeignKey(Owner, related_name="links", on_delete=models.CASCADE)

    def __str__(self):
        return f"Link {self.alias}"


class Click(models.Model):
    origin_ip = models.GenericIPAddressField()
    country = models.CharField(max_length=100)
    user_agent = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    link = models.ForeignKey(Link, related_name="clicks", on_delete=models.CASCADE)

    def __str__(self):
        return f"Click for {self.link.alias}"

backend/shortener/forms.py
from django import forms


class LinkPasswordForm(forms.Form):
    password = forms.CharField(max_length=12, required=True)

    def __init__(self, *args, link, **kwargs):
        super().__init__(*args, **kwargs)
        self._link = link

    def clean_password(self):
        password = self.cleaned_data["password"]

        if password != self._link.password:
            raise forms.ValidationError("Password doesn't match.")
        return password

backend/shortener/api/views.py
from rest_framework.generics import (
    CreateAPIView,
    DestroyAPIView,
    ListAPIView,
    RetrieveAPIView,
    get_object_or_404,
)
from rest_framework.response import Response
from rest_framework.views import APIView

from shortener.api.serializers import (
    LinkClicksSerializer,
    LinkCreateSerializer,
    LinkListSerializer,
    OwnerSerializer,
)
from shortener.models import Click, Link, Owner


class OwnerCreateAPIView(CreateAPIView):
    serializer_class = OwnerSerializer


class OwnerRetrieveAPIView(RetrieveAPIView):
    queryset = Owner.objects.all()
    serializer_class = OwnerSerializer


class LinkCreateAPIView(CreateAPIView):
    serializer_class = LinkCreateSerializer


class LinkListDestroyAPIView(DestroyAPIView, ListAPIView):
    serializer_class = LinkListSerializer

    def get_object(self):
        pk = self.kwargs["pk"]
        return get_object_or_404(Owner.objects.all(), pk=pk)

    def perform_destroy(self, instance: Owner):
        instance.links.all().delete()

    def get_queryset(self):
        owner = self.kwargs["pk"]
        return Link.objects.filter(owner=owner)


class AliasAvailabilityAPIView(APIView):
    def get(self, request, alias):
        if Link.objects.filter(alias=alias).exists():
            return Response(status=409)
        return Response()


class LinkClicksListAPIView(ListAPIView):
    serializer_class = LinkClicksSerializer

    def get_queryset(self):
        owner = self.kwargs["owner"]
        alias = self.kwargs["alias"]
        return Click.objects.filter(link__alias=alias, link__owner=owner)

backend/shortener/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import View

from shortener.forms import LinkPasswordForm
from shortener.models import Link
from shortener.signals import link_clicked


class ToTargetView(View):
    def get(self, request, alias):
        link = get_object_or_404(Link, pk=alias)
        link_clicked.send(sender=ToTargetView, link=link, request=request)

        if link.password:
            return render(request, "shortener/protected_link.html", context={"alias": alias})
        return redirect(to=link.target_url)

    def post(self, request, alias):
        link = get_object_or_404(Link, pk=alias)
        form = LinkPasswordForm(data=request.POST, link=link)

        if form.is_valid():
            return redirect(to=link.target_url)
        return render(
            request, "shortener/protected_link.html", context={"form": form, "alias": alias}
        )

backend/shortener/templates/shortener/protected_link.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Password Protected Link</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
  <style>
    .mantine-button {
      color: white;
      font-weight: 600;
      background-color: #0ca678;
      border-radius: 4px;
      border: none;
      height: 36px;
      padding-inline: 18px;
      cursor: pointer;
    }

    .mantine-button:hover {
      background-color: #099268;
    }
  </style>
</head>
<body>
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-half">
        <div class="title is-size-5 has-text-centered">Owner of this link protected it with a password</div>
        <form class="box" method="post" action="{% url 'shortener:to_target' alias=alias %}">
          {% csrf_token %}
          <div class="field">
            <label class="label" for="password">Link password</label>
            <div class="control">
              <input name="password" id="password" type="password" class="input" value="{{ form.password.value }}">
            </div>
            {% if form and form.password.errors %}
              {% for error in form.password.errors %}
                <p class="help is-danger">{{ error }}</p>
              {% endfor %}
            {% endif %}
          </div>
          <div class="field">
            <div class="control">
              <button type="submit" class="mantine-button">Go ahead!</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
</body>
</html>